### ISSUE TITLE
Creating stereo frame pairs from monocular video to train monodepth2

### ISSUE THREAD

**Issue by meder411** [nianticlabs/stereo-from-mono#2]
As this work is from Niantic, who is also responsible for monodepth2, I am curious (1) if you have been able to leverage stereo-from-mono to generate stereo video from monocular video, and if so, (2) if those generated stereo videos produce the same depth estimation benefits with monodepth2 as that paper shows for real stereo videos vs. monocular videos. Have you tried this type of experiment? If so, how does it work out? To be honest, I thought this experiment would be in the paper for sure. I am particularly curious about what type of temporal consistency you can expect frame-to-frame.

**Comment by JamieWatson683** [comment]
Hi, thanks for your interesting question, and sorry for the delay.

No, unfortunately we haven't tried such an experiment as the focus of the paper was on improving stereo depth estimation rather than monocular - however I can imagine leveraging the stereo estimates to improve mono (such as in a vein similar to [depth hints](https://github.com/nianticlabs/depth-hints)).

Is the experiment you are suggesting to use our method to synthesise "right" images from monocular "left" images, and train monodepth2 using stereo reprojection (i.e. the "S" case in the paper)? 

If so, I can think of a couple of potential issues. The first is where to get your initial monocular estimates to generate the synthetic images. If these come from MiDaS/Megadepth etc, then you would be benefitting from additional data. If instead you first train monodepth2 on the monocular video (i.e. the "M" setting) and then use these estimates to synthesise "right" images, and finally train monodepth using stereo reprojection, you will effectively be teaching the network to "be like itself" - it would be the same to skip the reprojection loss step and just supervise on the monocular estimates themselves. I can't see how this would improve performance necessarily.

Please let me know if I have misunderstood the question, or if my reply doesn't make sense.

Thanks,
Jamie
